table_urls = {
    'ADB - Asian Development Bank': '/alliances/adb-asian-development-bank.php',
    #'ALBA - Bolivarian Alliance for America': '/alliances/alba-bolivarian-alliance-for-america.php',
    'APEC - Asia-Pacific Economic Cooperation': '/alliances/apec-asia-pacific-economic-cooperation.php',
    'ASEAN - Association of Southeast Asian Nations': '/alliances/asean-association-of-southeast-asian-nations.php',
    'African Union': '/alliances/african-union.php',
    'Arab League': '/alliances/arab-league.php',
    # 'BRICS': '/alliances/brics.php',
    # 'CACM - Central American Common Market': '/alliances/cacm-central-american-common-market.php',
    # 'CAN - Andean Community of Nations': '/alliances/can-andean-community-of-nations.php',
    'CARICOM - Caribbean Community and Common Market': '/alliances/caricom-caribbean-community-and-common-market.php',
    'CELAC - Community of Latin American and Caribbean States': '/alliances/celac-community-of-latin-american-and-caribbean-states.php',
    # 'CEMAC - Economic and Monetary Community of Central Africa': '/alliances/cemac-economic-and-monetary-community-of-central-africa.php',
    # 'CIS - Commonwealth of Independent States': '/alliances/cis-commonwealth-of-independent-states.php',
    'COMESSA - Community of Sahel-Saharan States': '/alliances/comessa-community-of-sahel-saharan-states.php',
    'Commonwealth of Nations': '/alliances/commonwealth-of-nations.php',
    # 'EAC - East African Community': '/alliances/eac-east-african-community.php',
    'ECOWAS - Economic Community of West African States': '/alliances/ecowas-economic-community-of-west-african-states.php',
    # 'EEU - Eurasian Economic Union': '/alliances/eeu-eurasian-economic-union.php',
    # 'EFTA - European Free Trade Association': '/alliances/efta-european-free-trade-association.php',
    'EMU - Economic and Monetary Union': '/alliances/emu-economic-and-monetary-union.php',
    'European Union': '/alliances/european-union.php',
    'G20 - Developing Nations': '/alliances/g20-developing-nations.php',
    'G20 - Group of Twenty': '/alliances/g20-group-of-twenty.php',
    'G33 - Forum for developing countries': '/alliances/g33-forum-for-developing-countries.php',
    # 'G7plus - Group of Fragile States': '/alliances/g7plus-group-of-fragile-states.php',
    'G8 - Group of Eight': '/alliances/g8-group-of-eight.php',
    'GCC - Gulf Cooperation Council': '/alliances/gcc-gulf-cooperation-council.php',
    # 'Maghreb': '/alliances/maghreb.php',
    # 'Mashrek': '/alliances/mashrek.php',
    # 'Mercosur - Mercado Común del Sur': '/alliances/mercosur-mercado-comun-del-sur.php',
    # 'NAFTA - North American Free Trade Agreement': '/alliances/nafta-north-american-free-trade-agreement.php',
    'NATO - North Atlantic Treaty Organization': '/alliances/nato-north-atlantic-treaty-organization.php',
    'Non-Aligned Movement': '/alliances/non-aligned-movement.php',
    # 'OAPEC - Organization for Arabian Petroleum Exporting Countries': '/alliances/oapec-organization-for-arabian-petroleum-exporting-countries.php',
    'OAS - Organization of American States': '/alliances/oas-organization-of-american-states.php',
    'OECD': '/alliances/oecd.php',
    # 'OECS - Organization of Eastern Caribbean States': '/alliances/oecs-organization-of-eastern-caribbean-states.php',
    'OIC - Organization of Islamic Cooperation': '/alliances/oic-organization-of-islamic-cooperation.php',
    'OPEC - Organization of Petroleum Exporting Countries': '/alliances/opec-organization-of-petroleum-exporting-countries.php',
    'OSZE': '/alliances/osze.php',
    # 'SACU - Southern African Customs Union': '/alliances/sacu-southern-african-customs-union.php',
    'SADC - Southern African Development Community': '/alliances/sadc-southern-african-development-community.php',
    # 'SICA - Central American Integration System': '/alliances/sica-central-american-integration-system.php',
    'Schengen Countries': '/alliances/schengen-countries.php',
    'TPP - Trans-Pacific Partnership': '/alliances/tpp-trans-pacific-partnership.php',
    # 'Turkic Council': '/alliances/turkic-council.php',
    # 'UEMOA - Economic and Monetary Community of West Africa': '/alliances/uemoa-economic-and-monetary-community-of-west-africa.php',
    'UN - United Nations': '/alliances/un-united-nations.php',
    'UNESCO': '/alliances/unesco.php',
    'USAN - Union of South American Nations': '/alliances/usan-union-of-south-american-nations.php',
    # 'Visegrad': '/alliances/visegrad.php',
    'WTO - World Trade Organization': '/alliances/wto-world-trade-organization.php'
}